development:
  secret_key_base: abc123
  devise: zxc321

test:
  secret_key_base: abc123
  devise: zxc321

production:
  secret_key_base: <%= ENV['SECRET_COOKIE_TOKEN'] %>
  airbrake_api_key:  <%= ENV['AIRBRAKE_API_KEY'] %>
  devise: <%= ENV['DEVISE_SECRET'] %>
  google_key: <%= ENV['GOOGLE_KEY'] %>
  google_secret: <%= ENV['GOOGLE_SECRET'] %>
  facebook_key: <%= ENV['FACEBOOK_KEY'] %>
  facebook_secret: <%= ENV['FACEBOOK_SECRET'] %>
  intercom_app_id: <%= ENV['INTERCOM_APP_ID'] %>
  intercom_app_secret: <%= ENV['INTERCOM_APP_SECRET'] %>
  intercom_app_api_key: <%= ENV['INTERCOM_APP_API_KEY'] %>
  omni_contacts_google_key: <%= ENV['OMNI_CONTACTS_GOOGLE_KEY'] %>
  omni_contacts_google_secret: <%= ENV['OMNI_CONTACTS_GOOGLE_SECRET'] %>

  #config.api_key = Rails.application.secrets.airbrake_api_key
